language: crystal

crystal:
  - latest
  - nightly

script:
  - crystal spec

after_success:
  - crystal docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    branch: gh-pages